# Generated by Django 4.2.8 on 2025-12-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('sales_growth', models.FloatField(blank=True, null=True)),
                ('median_sales_growth', models.FloatField(blank=True, null=True)),
                ('dividend_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_rating', models.CharField(choices=[('GOOD', 'Good Financial Health'), ('BAD', 'Poor Financial Health'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('pros', models.TextField(help_text='Comma-separated pros')),
                ('cons', models.TextField(help_text='Comma-separated cons')),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.company')),
            ],
        ),
    ]
